export type CaseStudyGalleryItem = {
  id: number;
  slug: string;
  clientName: string;
  title: string;
  category: string;
  shortDescription: string;
  concept: string;
  year: number;
  services: string[];
  colorTheme: string;
  accent: string;
  gradFrom: string;
  gradTo: string;
  image: string;
  youtube?: string;
  /** Direct MP4 URLs (e.g. Cloudinary) — played inline on the detail page; takes precedence over `youtube`. */
  videos?: string[];
  order: number;
  /** 'tech' studies use the rich section fields below + a /tech image. */
  track?: 'film' | 'tech';
  overview?: string;
  challenge?: string;
  idea?: string;
  experienceIntro?: string;
  experienceItems?: string[];
  impact?: { value?: string; label: string }[];
  whyItWorked?: string;
};

const YT = (id: string) => `https://img.youtube.com/vi/${id}/hqdefault.jpg`;

export const caseStudies: CaseStudyGalleryItem[] = [
  {
    id: 1, slug: 'dharma-production', clientName: 'Dharma Productions', title: 'Sunny Sanskari Ki Tulsi Kumari',
    category: 'Film Marketing · Romantic Comedy',
    shortDescription: 'Turning cast chemistry, music trends, and chaos into a high-voltage social ecosystem where romance sold itself.',
    concept: "Rom-coms don't thrive on subtlety — they thrive on chaos, chemistry, and cultural noise. For Sunny Sanskari Ki Tulsi Kumari, we leaned fully into that truth, turning cast energy, heartbreak, and music trends into a high-voltage social ecosystem where chaos sold romance.\n\nThe campaign was built around the infectious chemistry of Varun Dhawan and Janhvi Kapoor, amplified through songs, reels, memes, and unfiltered shoot content. Rohit and Sanya's love for dance became a cultural trigger, pushing audiences to create millions of reels using the film's tracks — especially Bijuria and Panwadi, whose hook steps quickly took over Instagram feeds.\n\nInstead of polished promotions, the team embraced messiness: fun, chaotic cast videos where heartbreak and entertainment co-existed as the central narrative. AI-led creative units were introduced to break the cookie-cutter rom-com feed, giving Dharma's social presence a fresh, disruptive edge.\n\nBy making chaos and entertainment the heroes, the campaign fueled speculation, fandom debates, and repeat engagement — turning 'who ends up with whom' into a shared cultural question. The result was sustained buzz, massive music-led virality, and a strong emotional connect that positioned Sunny Sanskari Ki Tulsi Kumari as a celebration of modern love, confusion, and second chances.",
    year: 2025, services: ['Film Marketing', 'Social Media', 'Influencer', 'AI Creative'],
    colorTheme: '#e0197d', accent: '#e0197d', gradFrom: '#3d0028', gradTo: '#1a0015',
    image: YT('9FUd-D4FWjw'), youtube: '9FUd-D4FWjw', order: 1,
  },
  {
    id: 2, slug: 'kesari-chapter-2', clientName: 'Dharma Productions', title: 'Kesari Chapter 2',
    category: 'Film Marketing · Historical',
    shortDescription: "Turning passive spectators into active witnesses of India's forgotten courtroom history through 'Witness the History'.",
    concept: "In an entertainment-heavy landscape where film promotions often rely on spectacle, song launches, and predictable hype, marketing a century-old courtroom trial for Gen Z needed a radical shift. With Kesari Chapter 2, we chose to break convention by turning audiences from passive spectators into active witnesses through the campaign 'Witness the History.'\n\nThe campaign began with a disruptive, all-platform blank-screen teaser that hijacked feeds and sparked nationwide curiosity. This bold silence set the tone for a story that history had forgotten but needed to be heard. Progressive reveals of Akshay Kumar, R Madhavan, and Ananya Panday followed, carefully balancing mass appeal with cultural relevance.\n\nWe amplified the first-ever Akshay vs Maddy courtroom face-off as pop-culture fuel, igniting organic fandom conversations and dialogue-led storytelling. By rooting the narrative in emotion, confrontation, and truth, the campaign summoned a new generation to witness C. Sankaran Nair's forgotten legal battle against the British Empire.\n\nThrough social-first disruption and culturally resonant storytelling, Kesari Chapter 2 was positioned not just as a film, but as a national moment — one that revived history, rebuilt star power, and made the past feel urgent, visceral, and unmissable today.",
    year: 2025, services: ['Film Marketing', 'Creative Strategy', 'Digital', 'Social Media'],
    colorTheme: '#c4820a', accent: '#e09420', gradFrom: '#2d1800', gradTo: '#1a0e00',
    image: YT('r-7g08INMSI'), youtube: 'r-7g08INMSI', order: 2,
  },
  {
    id: 3, slug: 'maa-devgn', clientName: 'Devgn Films', title: 'MAA',
    category: 'Film Marketing · Horror',
    shortDescription: "Blending supernatural fear with maternal strength — replacing surnames with mothers' names in film credits, a first in Indian cinema.",
    concept: "In a market where horror-comedy dominates box office success, launching a pure horror film demanded a strategic expansion of both audience and universe. With MAA, we set out to grow the horror fanbase by blending supernatural fear with the emotional force of maternal strength — anchored in the idea 'End credit goes to MAA.'\n\nThe campaign strategically inducted MAA into a larger supernatural arc by leveraging the Shaitaan universe, introducing R Madhavan at the trailer launch to instantly deepen credibility and intrigue among horror loyalists. To broaden appeal beyond core horror audiences, we reframed the narrative around faith, belief, and motherhood — most powerfully by replacing surnames with mothers' names in the film credits, a first in Indian cinema.\n\nTo amplify emotional resonance, icons like Kajol and Usha Uthup came together during the song launch to celebrate maternal strength. For hardcore horror fans, immersive fear-first experiences were rolled out through paranormal-themed podcasts, terror train takeovers, and atmospheric digital storytelling that visualised a formless evil using AI-led narratives.\n\nBy oscillating between fear and faith, the campaign positioned MAA as more than just a horror release — it became an emotionally charged universe where belief stands as the ultimate weapon against evil, expanding the genre's appeal and bringing pure horror back into mainstream cultural conversation.",
    year: 2025, services: ['Film Marketing', 'Universe Strategy', 'Experiential', 'AI Storytelling'],
    colorTheme: '#6b0080', accent: '#8800a0', gradFrom: '#0a0010', gradTo: '#050008',
    image: YT('zwtZj6YB9xk'), youtube: 'zwtZj6YB9xk', order: 3,
  },
  {
    id: 4, slug: 'son-of-sardaar-2', clientName: 'Devgn Films', title: 'Son Of Sardaar 2',
    category: 'Film Marketing · Comedy',
    shortDescription: 'Fun itself was the strategy. #PehlaTuDujaTu turned even trolls into participants.',
    concept: "In a crowded comedy landscape where humour often blends into sameness, standing out meant shifting focus from promotion to pure vibe. For Son Of Sardaar 2, we made fun itself the strategy with the campaign 'Jahan Son Hai, Wahan Fun Hai' — selling the energy of the film, not just the film.\n\nThe campaign leaned heavily into the cast's natural chemistry, converting behind-the-scenes humour into pop-culture momentum. What began as a simple step evolved into the viral trend #PehlaTuDujaTu, turning even trolls into participants. Quick, exclusive social assets featuring the ensemble were created at speed, capturing spontaneous moments that felt authentic and infectious.\n\nTo deepen engagement, casual round-table interactions showcased the cast's camaraderie, while long-form content like a cast podcast extended the fun beyond short clips. Audience nostalgia for the original film was tapped into with the release of the PO PO song, reinforcing familiarity while reigniting excitement.\n\nAmplified by third-party pages and fan communities, the campaign firmly established one idea across platforms: Fun = Son Of Sardaar 2. By letting audiences witness the cast enjoying themselves, the campaign rebuilt buzz, reignited conversation, and made people want to join the fun long before release.",
    year: 2025, services: ['Film Marketing', 'Social Media', 'Viral Content', 'Podcast'],
    colorTheme: '#e05500', accent: '#f06000', gradFrom: '#3a1a00', gradTo: '#1a0c00',
    image: YT('HSX_KPfbP1o'), youtube: 'HSX_KPfbP1o', order: 4,
  },
  {
    id: 5, slug: 'sitaare-zameen-par', clientName: 'Aamir Khan Productions', title: 'Sitaare Zameen Par',
    category: 'Film Marketing · Entertainment',
    shortDescription: "An imperfectly perfect teaser — handcrafted cutout reveals designed to disrupt the scroll before the trailer drop.",
    concept: "In a social feed dominated by algorithmically perfect visuals and polished teaser drops, standing out meant doing the opposite. For Sitaare Zameen Par, we chose to disrupt the scroll by embracing imperfection with 'Imperfectly Perfect Teaser' — a handcrafted, tactile announcement unit designed to spark curiosity ahead of the trailer launch.\n\nInstead of sleek motion graphics, the campaign leaned into a pop-up cutout aesthetic. Printed images of the film's 10 Sitaare were revealed one by one, culminating in the reveal of Aamir Khan and the announcement that the trailer would drop the very next day. The deliberate roughness and handmade feel broke visual monotony and instantly caught attention.\n\nRolled out across social platforms, the imperfect design became its biggest strength — inviting intrigue, conversation, and organic pickup by fan and media pages. By rejecting visual perfection and leaning into playful honesty, Sitaare Zameen Par set the tone for what was to come: a film that's raw, emotional, and refreshingly human — long before audiences hit play on the trailer.",
    year: 2025, services: ['Film Marketing', 'Creative Strategy', 'Social Media'],
    colorTheme: '#0055cc', accent: '#0066ff', gradFrom: '#001840', gradTo: '#000f28',
    image: YT('YH6k5weqwy8'), youtube: 'YH6k5weqwy8', order: 5,
  },
  {
    id: 6, slug: 'ashok-leyland-diwali', clientName: 'Ashok Leyland', title: '#KhushiyonKiSteering',
    category: 'Commercial Vehicles · Festive Campaign',
    shortDescription: "Positioning Ashok Leyland as the unseen force that powers India's Diwali — the brand that keeps the nation moving.",
    concept: "Festive advertising during Diwali is largely dominated by consumer brands focusing on emotion, family, and celebration, while B2B brands often remain in the background. With #KhushiyonKiSteering, we set out to change that narrative by positioning Ashok Leyland as the unseen force that powers India's festive joy.\n\nThe campaign highlighted how Diwali celebrations across the country are made possible by countless journeys — sweets, diyas, fabrics, and essentials travelling from different regions to one home. Instead of overt product messaging, Ashok Leyland's presence was subtly woven into the story through creative transitions using truck elements like steering wheels and tyres.\n\nBy emotionally anchoring the brand to Diwali and showcasing its role as an enabler of togetherness, the campaign made a traditionally B2B brand culturally relevant, emotionally resonant, and central to India's festive supply chain — reinforcing Ashok Leyland as the brand that keeps the nation moving, especially when it matters most.",
    year: 2024, services: ['Brand Film', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#1a3070', accent: '#1a6aff', gradFrom: '#0a1840', gradTo: '#050e20',
    image: YT('37CCZAHaYx8'), youtube: '37CCZAHaYx8', order: 6,
  },
  {
    id: 7, slug: 'ashok-leyland-kargil', clientName: 'Ashok Leyland', title: '#EyeOfTheStallion',
    category: 'Automotive · Defence · AI Film',
    shortDescription: "India's first large-scale AI-led brand film — narrating Kargil from the Stallion vehicle's perspective using generative AI.",
    concept: "National-day tributes often follow a familiar format: stock visuals, archival footage, and predictable narratives. For Kargil Vijay Diwas, Ashok Leyland chose to break that pattern with #EyeOfTheStallion — a first-of-its-kind tribute told entirely through Generative AI, making it one of the earliest large-scale AI-led brand films in the Indian automotive category.\n\nInstead of recounting the war through human voices alone, the story was narrated from a fresh and deeply emotional point of view: the Ashok Leyland Stallion — a vehicle that has served the Indian Army for decades. The Stallion became the silent witness carrying soldiers, supplies, and the wounded across the unforgiving terrain of Kargil. The film unfolded as a series of memories seen through its eyes, blending courage, loss, and resilience.\n\nGenerative AI enabled the recreation of war-time landscapes, mountain routes, convoys, and memory-like moments that are impossible to film today. Tools like ChatGPT, Runway, Higgsfield, Veo, Google AI Studio, and Hailuo AI were used to craft hyper-realistic visuals, while the voiceover and music remained human-led to preserve emotional authenticity.\n\nReleased across Ashok Leyland's social platforms, the film struck a strong emotional chord, earning widespread appreciation from defence communities, veterans, employees, and the public. By linking back to the brand promise 'Koi Manzil Door Nahin', #EyeOfTheStallion demonstrated how AI can be used not as a gimmick, but as a respectful, culturally sensitive storytelling tool.",
    year: 2024, services: ['AI Film Production', 'Brand Strategy', 'Social Media'],
    colorTheme: '#2d4a00', accent: '#4a7a00', gradFrom: '#0f1a00', gradTo: '#080d00',
    image: YT('v2c1uigYjLk'), youtube: 'v2c1uigYjLk', order: 7,
  },
  {
    id: 33, slug: 'ashok-leyland-zidd-wahi-manzil-nayi', clientName: 'Ashok Leyland', title: 'Zidd Wahi Manzil Nayi',
    category: 'Commercial Vehicles · WPL Campaign',
    shortDescription: "An Ashok Leyland × Mumbai Indians WPL film — success raises the stage, but never changes the discipline it takes to get there. Kuch Nahi Badla.",
    concept: "Success changes how the world sees you. It doesn't change what it takes to keep moving forward.\n\nWomen's cricket has reached new heights — earning recognition, applause, and packed stadiums. But behind every boundary, wicket, and victory lies the same relentless discipline, sacrifice, and hard work that existed before the spotlight arrived.\n\nOur film celebrates this mindset through the thought 'Kuch Nahi Badla.' The expectations are higher, the stage is bigger, but the commitment remains unchanged. Every training session, every early morning, every challenge still demands the same determination.\n\nDrawing a parallel between elite athletes and Ashok Leyland, the film highlights a shared belief: success isn't built on one great moment — it's built on showing up and performing consistently, every single day.\n\nBecause no matter how far you've come, the journey continues. And for those who never stop pushing forward, Koi Manzil Door Nahin.",
    year: 2026, services: ['Brand Film', 'Sports Marketing', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#004ba0', accent: '#1a6aff', gradFrom: '#001a40', gradTo: '#00091f',
    image: YT('pW8Z44YLtKA'), youtube: 'pW8Z44YLtKA', order: 33,
  },
  {
    id: 34, slug: 'ashok-leyland-whistle-podu-please', clientName: 'Ashok Leyland', title: 'Whistle Podu Please',
    category: 'Commercial Vehicles · IPL Campaign',
    shortDescription: "An Ashok Leyland × Chennai Super Kings film connecting two cultures that keep India moving — from 'Horn OK Please' on the highway to 'Whistle Podu' in the stands.",
    concept: "Some signals don't need an introduction. They're understood instantly — on the road and on the cricket field.\n\nWhistle Podu Please brings together Ashok Leyland and Chennai Super Kings through a shared language of action. From the familiar 'Horn OK Please' seen on highways to the iconic 'Whistle Podu' chant that echoes through stadiums, the film celebrates two cultures that keep India moving. Through a series of energetic, whistle-led moments, the film draws parallels between truck drivers and cricketing champions — both driven by precision, teamwork, and the spirit to keep going.\n\nBecause whether you're navigating roads or chasing victories, one signal says it all. When it's time to move, it's time to Whistle Podu Please.",
    year: 2026, services: ['Brand Film', 'Sports Marketing', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#c4a000', accent: '#f0c000', gradFrom: '#2a2100', gradTo: '#141000',
    image: YT('o2h-9sNPAo4'), youtube: 'o2h-9sNPAo4', order: 34,
  },
  {
    id: 35, slug: 'ashok-leyland-she-drives-it', clientName: 'Ashok Leyland', title: 'She Drives It',
    category: "Commercial Vehicles · Women's Day",
    shortDescription: "A Women's Day film with Ashok Leyland and the Mumbai Indians Women's Team — celebrating women who don't wait for change, they drive it. #SheDrivesIt.",
    concept: "Progress doesn't happen by chance. It is driven by people who refuse to stay within the boundaries set for them.\n\n#SheDrivesIt celebrates the women who continue to move India forward — on the field, on the road, and in every sphere where determination creates change. Bringing together Ashok Leyland and the Mumbai Indians Women's Team, the film draws a powerful parallel between athletes and trailblazers who succeed through resilience, discipline, and an unwavering belief in their abilities.\n\nEvery run scored, every challenge overcome, and every barrier broken is proof that progress is powered by those willing to keep pushing ahead. This Women's Day, Ashok Leyland celebrates the spirit of women who don't wait for change — they drive it.\n\nBecause when ambition takes the wheel, no destination is too far.",
    year: 2026, services: ['Brand Film', 'Sports Marketing', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#c42b6e', accent: '#e0197d', gradFrom: '#2a0a1c', gradTo: '#14040e',
    image: YT('Hx7l9Uoj7CQ'), youtube: 'Hx7l9Uoj7CQ', order: 35,
  },
  {
    id: 36, slug: 'ashok-leyland-mothers-day', clientName: 'Ashok Leyland', title: "Mother's Day",
    category: "Commercial Vehicles · Mother's Day",
    shortDescription: "A Mother's Day film rooted in the Indian ritual of seeking a mother's blessing before a journey — positioning Ashok Leyland as the second layer of protection on every road.",
    concept: "The film is built on a simple yet deeply rooted Indian insight: before setting out on an important journey, many people seek their mother's blessings. This emotional ritual transcends regions, languages, and cultures, making it a universally relatable moment.\n\nAshok Leyland connects this insight to its brand promise, 'Koi Manzil Door Nahin', by portraying how every journey begins with a mother's care and is safeguarded on the road through Ashok Leyland's reliable vehicles. Through a series of fast-paced, emotionally rich vignettes featuring drivers and transport professionals from different walks of life, the film showcases mothers blessing their children before they embark on their journeys.\n\nThe narrative subtly positions Ashok Leyland as an extension of that protective care — ensuring safety, reliability, and confidence on every road. Rather than focusing on product features, the film humanizes the trucking ecosystem and celebrates the emotional bond between mothers and those who keep India moving.\n\nThe core message: a mother's blessing is the first layer of protection; Ashok Leyland is the second — helping every driver reach their destination safely, because no destination is too far when you're protected by care and trust.",
    year: 2026, services: ['Brand Film', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#a8324a', accent: '#e0395a', gradFrom: '#2a0a12', gradTo: '#150509',
    image: YT('tMP_euOcGx4'), youtube: 'tMP_euOcGx4', order: 36,
  },
  {
    id: 37, slug: 'ashok-leyland-built-like-santa', clientName: 'Ashok Leyland', title: 'Built Like Santa',
    category: 'Commercial Vehicles · Festive Campaign',
    shortDescription: "A Christmas film drawing a parallel between Santa's never-miss-a-destination journey and the reliability of Ashok Leyland trucks — celebrating those Built Like Santa.",
    concept: "Christmas is a season of giving — where joy, warmth, and togetherness travel across cities, towns, and remote corners of the country to reach every home.\n\nWhile the world celebrates Santa as the bearer of Christmas magic, there are countless real-life heroes working behind the scenes to make those celebrations possible. Through long nights, challenging roads, and distant destinations, they ensure that gifts, essentials, and festive cheer arrive exactly where they are needed.\n\nOur film draws a heartwarming parallel between Santa's legendary journey and the unwavering reliability of Ashok Leyland trucks. Just as Santa never misses a destination, Ashok Leyland powers the journeys that connect people, deliver happiness, and keep the spirit of Christmas moving.\n\nBecause Christmas magic isn't just about the gifts that arrive — it's about the people and journeys that make them possible. This Christmas, Ashok Leyland celebrates those who are Built Like Santa: always on the move, delivering joy, no matter how far the destination.",
    year: 2025, services: ['Brand Film', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#9c1f1f', accent: '#e03434', gradFrom: '#2a0808', gradTo: '#140404',
    image: YT('Mr8fSjgj-qI'), youtube: 'Mr8fSjgj-qI', order: 37,
  },
  {
    id: 8, slug: 'zydus-easiest-exam', clientName: 'Zydus Lifesciences', title: 'Easiest Exam',
    category: 'Healthcare · Public Awareness',
    shortDescription: "A podcast series hosted by breast cancer survivor Hina Khan reframing breast self-examination as the simplest, most powerful tool women already possess.",
    concept: "Breast cancer awareness in India is widespread, yet early detection through breast self-examination remains low due to fear, stigma, and lack of relatable communication. With Easiest Exam, Zydus set out to bridge this gap by shifting the conversation from awareness to understanding — and from instruction to empathy.\n\nAt the heart of the campaign was a podcast series that treated breast health not as a medical lecture, but as a human conversation. Hosted by Hina Khan, a breast cancer survivor herself, Easiest Exam created a safe, credible, and mobile-first space where oncologists and survivors came together to simplify complex medical information, bust myths, and reduce fear around early detection.\n\nThe podcast reframed breast self-examination as the simplest, most powerful tool women already possess — their own hands. By blending medical credibility with lived experience, each episode gently guided listeners from hesitation to confidence, making early detection feel personal, approachable, and achievable rather than intimidating.\n\nThe campaign was supported by a larger content ecosystem including print, digital, and social touchpoints that directed audiences to deeper engagement through the podcast. Together, these elements transformed symbolic awareness into meaningful action, encouraging women to listen, learn, and take agency over their health.",
    year: 2024, services: ['Podcast Production', 'Content Strategy', 'Digital', 'Influencer'],
    colorTheme: '#9b35cc', accent: '#c060e0', gradFrom: '#1a0028', gradTo: '#0d0015',
    image: YT('EQvD2DvnE0M'), youtube: 'EQvD2DvnE0M', order: 8,
  },
  {
    id: 9, slug: 'zydus-flu-vaccine', clientName: 'Zydus Lifesciences', title: 'Flu Vaccine Liya Kya?',
    category: 'Healthcare · Preventive Health',
    shortDescription: "Normalising flu vaccination as a yearly habit through radio storytelling and culturally intuitive social nudges.",
    concept: "Despite high awareness around seasonal flu, vaccination uptake in India remains low — largely due to complacency and the familiar 'ho jayega' mindset. With the launch of Vaxiflu-4, India's first quadrivalent flu vaccine, Zydus set out to normalise flu vaccination as a yearly health habit, not a crisis-driven decision.\n\nInstead of fear-based medical messaging, the campaign introduced a culturally intuitive nudge: 'Flu Vaccine Liya Kya?' — a line that sounds like everyday small talk, yet carries real preventive intent. By reframing vaccination as a simple social check-in — much like asking about food, travel, or health — the campaign transformed a medical action into a conversational habit.\n\nRadio became the lead medium for this behavioural shift. Through slice-of-life storytelling, routine daily questions were replaced with one that truly mattered, cutting through clutter with warmth, familiarity, and repetition. Partnering with Radio Mirchi, multilingual, high-frequency spots were rolled out across prime cities and time bands to drive recall at scale.\n\nThe conversation was extended beyond airwaves through RJ-led social content, where trusted radio voices carried the message into digital spaces with credibility and relatability. By making prevention sound human, familiar, and timely, the campaign successfully turned flu vaccination into an everyday conversation.",
    year: 2024, services: ['Radio Campaign', 'Social Media', 'Brand Strategy', 'Influencer'],
    colorTheme: '#005580', accent: '#0088cc', gradFrom: '#001828', gradTo: '#000c14',
    image: YT('uy64MMydnJ0'), youtube: 'uy64MMydnJ0', order: 9,
  },
  {
    id: 10, slug: 'zydus-life-ka-filter', clientName: 'Zydus Lifesciences', title: '#LifeKaFilter',
    category: 'Healthcare · Public Awareness',
    shortDescription: "Using the everyday beverage filter metaphor to demystify kidney health and turn a complex medical topic into daily conversation.",
    concept: "Health communication often struggles to break through because medical science feels intimidating and distant. With #LifeKaFilter, we reframed kidney health into a simple, everyday idea — something everyone already understands. Just like every morning begins with a filter for tea or coffee, life itself depends on an internal filter: our kidneys.\n\nBy using the familiar metaphor of a beverage filter, the campaign demystified the complex role of kidneys and turned a daunting medical topic into a relatable, mainstream conversation. Instead of fear-based messaging, #LifeKaFilter focused on awareness, simplicity, and daily relevance — making people pause and reflect on what silently filters their lives every day.\n\nBorn from the urgent reality that Chronic Kidney Disease often goes undetected due to low awareness, the campaign built a large, credible content ecosystem. Expert-led podcasts with leading oncologists and nephrologists added depth and trust, while promo films, influencer hygiene content, and print integrations ensured scale and mass visibility.\n\nBy blending education with familiarity, and science with storytelling, #LifeKaFilter succeeded in making kidney health a part of everyday discourse, positioning Zydus Lifesciences as a brand committed not just to treatment, but to proactive public health awareness at scale.",
    year: 2025, services: ['Podcast', 'Content Production', 'Influencer', 'Digital'],
    colorTheme: '#c45000', accent: '#e06000', gradFrom: '#2a1000', gradTo: '#150800',
    image: YT('qnYpXHOVYY0'), youtube: 'qnYpXHOVYY0', order: 10,
  },
  {
    id: 11, slug: 'zydus-liver-ki-suno', clientName: 'Zydus Lifesciences', title: '#LiverKiSuno',
    category: 'Healthcare · Comedy Campaign',
    shortDescription: "Using humour with Johnny Lever, Jamie Lever & Suresh Menon to turn apathy around fatty liver disease into attention, conversation, and action.",
    concept: "Health awareness campaigns often rely on fear, statistics, or medical jargon — especially when the condition is serious. With #LiverKiSuno, we chose to flip that approach by using humour as the strategy, turning apathy around fatty liver disease into attention, conversation, and action.\n\nFatty liver affects nearly 40% of Indians, yet remains ignored because it shows no early symptoms and doesn't feel urgent. The key barrier wasn't lack of care — it was lack of relatability. So we gave the liver a voice. Through everyday humour, familiar situations, and culturally rooted comedy, the campaign made the liver 'complain' in ways people could instantly recognise and laugh with, without trivialising the science.\n\nBy collaborating with India's most trusted comedians — Johnny Lever, Jamie Lever, and Suresh Menon — the campaign transformed a silent, neglected condition into content people wanted to watch, share, and discuss at home. Humour became the hook, while medical credibility remained the backbone, ensuring the message stayed accurate, responsible, and impactful.\n\nBuilt on the simple, culturally intuitive idea of listening to your liver before it's forced to scream, #LiverKiSuno proved that laughter can be a powerful behavioural tool — repositioning preventive healthcare as something conversational, not clinical.",
    year: 2025, services: ['Brand Film', 'Comedy Content', 'Podcast', 'Social Media'],
    colorTheme: '#c4a000', accent: '#e0b800', gradFrom: '#1a1400', gradTo: '#0d0a00',
    image: YT('aQo7sFLPwGw'), youtube: 'aQo7sFLPwGw', order: 11,
  },
  {
    id: 12, slug: 'mumbai-indians', clientName: 'DHL × Mumbai Indians', title: ' #ThatsMyGame & Dil Se Indian',
    category: 'Logistics · IPL Campaign',
    shortDescription: "Two campaigns, one shoot — #ThatsMyGame and Dil Se Indian woven into the IPL's biggest social ecosystem.",
    concept: "During the IPL season, ad campaigns featuring cricketers dancing and singing on green screen backgrounds are ubiquitous. However, when tasked with creating a unique campaign proposition for DHL with Mumbai Indians, we decided to break the mold with #ThatsMyGame. This campaign had cricketers asserting that their game is cricket, not dancing or singing.\n\nBut we didn't stop there. Capitalising on the same shoot, we crafted a second campaign: 'Dil Se Indian.' This campaign showcased the indomitable spirit of the Mumbai Indians, capturing the essence and pride that lies in the heart of every Indian. We also subtly integrated the strengths of DHL, ensuring that the videos traveled easily across social feeds, maximising engagement and reach.\n\nTwo complete campaigns from one production day — a testament to efficient creative strategy that delivered maximum impact while respecting the client's resources and the players' time. Both campaigns performed strongly across social platforms, with #ThatsMyGame sparking conversation about authenticity in sports marketing and Dil Se Indian reinforcing the emotional bond between the team and its fans.",
    year: 2024, services: ['Brand Film', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#003f8a', accent: '#004fc4', gradFrom: '#00205b', gradTo: '#001845',
    image: YT('MJofvf2lBNY'), youtube: 'MJofvf2lBNY', order: 12,
  },
  {
    id: 13, slug: 'disney-india', clientName: 'Disney India', title: 'Disney Delicious Minis',
    category: 'Entertainment · Food Series',
    shortDescription: "A 24-episode food series marrying health with taste through Disney characters and two celebrity chefs.",
    concept: "Disney India has brought to us an array of stories that teach us something, entertain, and inspire generations. When tasked with creating branded content for Disney, we asked ourselves: how do we marry health with taste in a way that feels magical?\n\nThe answer was the 'Disney Delicious Minis' series — headlined by Chef Saransh Goila and Chef Chinu Vaze. With interesting takes on healthy recipes featuring Disney movie references and characters, it made a wholesome package for adults and kids alike.\n\nChef Saransh Goila, the author and winner of Food Food Maha Challenge, and Chef Chinu Vaze, a celebrity Chef, Host, and Writer, brought their unique expertise to a series of 24 short videos. Each episode balanced culinary creativity with the warmth and wonder of Disney's storytelling universe — turning healthy eating into a magical, entertaining experience.\n\nThe series proved that branded content works best when it genuinely entertains. By letting the chefs' personalities shine and the Disney characters add visual delight, Disney Delicious Minis became a destination series rather than just branded promotion — content families actually sought out and watched together.",
    year: 2024, services: ['Content Strategy', 'Video Production', 'Social Media'],
    colorTheme: '#003f8a', accent: '#1565c0', gradFrom: '#00205b', gradTo: '#001030',
    image: YT('qzHtzyuk_g4'), youtube: 'qzHtzyuk_g4', order: 13,
  },
  {
    id: 14, slug: 'danone-nurses-day', clientName: 'Danone', title: "Nurses' Day Tribute Film",
    category: 'Food · Healthcare',
    shortDescription: "A poignant tribute celebrating the selfless, motherly nature of paediatric nurses — the unsung heroes of early childhood.",
    concept: "A paediatric nurse is the first friend a newborn child meets — tenderly caring for them, feeding them, and nurturing them through their initial hours. In doing so, she often sacrifices time with her own children and family, yet carries out her duties with unwavering dedication.\n\nWhen tasked with creating a Nurses' Day asset for Danone India, we decided to illuminate this selfless, motherly nature of paediatric nurses through a poignant and touching film. This tribute celebrated and thanked the paediatric nurses — the unsung heroes who become the first friends and guardians of our children — honouring their relentless compassion and devotion.\n\nThe film became a cultural moment, resonating deeply with healthcare workers, parents, and audiences who recognised the quiet sacrifice nurses make every day. By anchoring Danone's purpose to maternal care and healthcare heroism, the brand positioned itself beyond nutrition — as a partner in nurturing and caring for the most vulnerable lives.",
    year: 2024, services: ['Brand Film', 'Healthcare Marketing', 'Social Media'],
    colorTheme: '#0066cc', accent: '#0080ff', gradFrom: '#001840', gradTo: '#000820',
    image: YT('D8cXWh7g2kk'), youtube: 'D8cXWh7g2kk', order: 14,
  },
  {
    id: 15, slug: 'icici-flash-trade', clientName: 'ICICI Direct', title: 'Flash Trade — The Turkish Ice-Cream',
    category: 'Banking · Campaign',
    shortDescription: "Positioning simple trading through a hilariously complex metaphor — the Turkish ice-cream experience that frustrates before it delights.",
    concept: "To bring out the easy and simple nature of ICICI Direct Flash Trade's user experience, we drew parallels with something completely opposite — the Turkish ice-cream experience: complex, teasy and sometimes frustrating. With unique POV shots putting viewers in the characters' shoes, a little inspiration from Wes Anderson, and a sprinkle of funny, we made this advertisement for ICICI Direct Flash Trade.\n\nA Turkish ice-cream experience is an emotional rollercoaster — excitement that builds into anxiety, then irritation, then anger. That is not what trading should feel like. Trading shouldn't be an emotional rollercoaster, but a simple experience of investment — which is exactly what ICICI Direct Flash Trade provides.\n\nThe campaign struck a chord with audiences through its uniqueness, wit, and relatable frustration. By inverting expectations and using humour to communicate product benefits, the film made financial services feel human, approachable, and even entertaining — a rare achievement in the BFSI category.",
    year: 2024, services: ['Brand Film', 'Campaign Strategy', 'Social Media'],
    colorTheme: '#ff9900', accent: '#ffaa00', gradFrom: '#331a00', gradTo: '#1a0d00',
    image: YT('4D4H43PBEEo'), youtube: '4D4H43PBEEo', order: 15,
  },
  {
    id: 16, slug: 'proteinx-abhiyaan', clientName: 'ProteinX India', title: 'Protein Abhiyaan Anthem',
    category: 'Fitness · Wellness',
    shortDescription: "A nation-building anthem celebrating protein as the source of strength for every Indian — the foundation of health and progress.",
    concept: "The people are the strength of this country, and their strength comes from protein. We conceptualised and shot the Protein Abhiyaan Anthem for ProteinX India — a celebration of how protein fuels the nation, from athletes to farmers, students to workers.\n\nThe anthem positioned protein not as a fitness supplement, but as a fundamental building block of Indian strength and progress. By connecting personal wellness with national pride, the campaign transcended typical fitness marketing and became a movement.\n\nThrough dynamic visuals, powerful messaging, and aspirational storytelling, Protein Abhiyaan Anthem became an iconic piece of content that resonated across demographics — proving that fitness and wellness could be celebrated as a collective, nation-wide mission rather than an individual pursuit.",
    year: 2024, services: ['Brand Film', 'Campaign Strategy', 'Social Media'],
    colorTheme: '#c41e3a', accent: '#e02a52', gradFrom: '#1a0a0e', gradTo: '#0d0507',
    image: YT('J4w6sjHgwlI'), youtube: 'J4w6sjHgwlI', order: 16,
  },
  {
    id: 17, slug: 'sandu-pharma-youth', clientName: 'Sandu Pharma', title: "A 122-Year-Old Brand For Today's Youth",
    category: 'Pharma · Brand Positioning',
    shortDescription: "Positioning a century-old ayurvedic brand as relevant to modern youth — honouring heritage while speaking the language of a new generation.",
    concept: "For a brand that has produced ayurvedic medicines for more than 100 years, it's a challenge to strike a balance between the age-old benefits of the science of Ayurveda and its communication to the ever-evolving, fast-paced consumer.\n\nWe made Sandu Pharma appeal to today's youth — honouring its heritage while speaking the language of a new generation. Instead of positioning Ayurveda as a nostalgic relic, we reframed it as an ancient science backed by modern understanding, meeting contemporary wellness needs.\n\nThrough relatable storytelling, contemporary aesthetics, and cultural resonance, the campaign proved that heritage brands can evolve without losing their soul. Sandu Pharma became a bridge between tradition and modernity — a brand your grandmother trusted that your generation would choose too.",
    year: 2024, services: ['Brand Film', 'Social Media', 'Campaign Strategy'],
    colorTheme: '#2d5016', accent: '#3d6b1f', gradFrom: '#0a0e04', gradTo: '#050707',
    image: YT('yK-Te8ceD64'), youtube: 'yK-Te8ceD64', order: 17,
  },
  {
    id: 18, slug: 'the-q-sabse-alag', clientName: 'The Q', title: 'Sabse Alag, Sabke Liye',
    category: 'Entertainment · Channel Positioning',
    shortDescription: "Establishing a channel's uniquely inclusive positioning — distinctly different, yet universally welcoming.",
    concept: "Right since its inception, The Q has been known for its distinctive strategy that brings the best of digital to TV. We conceptualised and established 'Sabse Alag, Sabke Liye' for the channel — capturing its uniquely inclusive positioning.\n\nThe campaign balanced The Q's core identity — being different, experimental, and forward-thinking — with its mission to remain accessible and welcoming to all. By leveraging the channel's unique content strategy and positioning it as both distinctly different AND universally relevant, the campaign carved a unique space in an overcrowded entertainment landscape.\n\nThrough integrated social and on-air content, the campaign successfully established The Q as the channel for people who wanted something different without sacrificing mass appeal — a rare positioning achievement.",
    year: 2024, services: ['Brand Strategy', 'Social Media', 'On-Air Marketing'],
    colorTheme: '#9d4edd', accent: '#b565f5', gradFrom: '#1a0033', gradTo: '#0d001a',
    image: YT('gGdQ1aL1LEY'), youtube: 'gGdQ1aL1LEY', order: 18,
  },
  {
    id: 19, slug: 'vibha-curious-kid', clientName: 'Vibha', title: 'Through The Eyes Of A Curious Kid',
    category: 'Non-Profit · Social Impact',
    shortDescription: "Reframing poverty not through pity, but through the unquenchable curiosity of a child — a celebration of potential over circumstance.",
    concept: "As an NGO, Vibha's challenge is raising funds. We needed to strike a chord with individual donors through great storytelling in the brand TVC, in order to motivate them to donate.\n\nWe didn't want to make the film a sad reflection on the kid's situation, but a happy, buoyant celebration of his curiosity. The kid's inquisitiveness became the hero of the campaign — travelling a full journey where it is ignored, made fun of, and even discouraged, but never truly fades away.\n\nBy shifting the narrative from 'help a poor child' to 'celebrate a curious mind', the campaign gave donors a reason to invest beyond guilt or charity — they were investing in potential, in dreams, and in the future. This reframing transformed donation from an act of sympathy into an act of belief and partnership.",
    year: 2024, services: ['Non-Profit Marketing', 'Brand Film', 'Social Media'],
    colorTheme: '#e85d04', accent: '#ff9500', gradFrom: '#1a0a00', gradTo: '#0d0500',
    image: YT('aUDe3d7HfUE'), youtube: 'aUDe3d7HfUE', order: 19,
  },
  {
    id: 20, slug: 'thailand-tourism', clientName: 'Thailand Tourism Board', title: 'Evoking Wanderlust For Thai Tourism',
    category: 'Tourism · Destination Marketing',
    shortDescription: "Repositioning Thailand as a destination of premium, aspirational experiences — moving beyond mass perceptions to luxury positioning.",
    concept: "Repositioning the brand in the minds of high-value customers was a critical but long-drawn exercise, because premium imagery is not Thailand's core positioning; it was seen as a mass product with no unique USP or luxury value; and myths and perceptions scare the uninitiated.\n\nWe set out to evoke our audience's wanderlust — recasting Thailand as a destination of premium, aspirational experiences. Through carefully curated visuals, emotional storytelling, and luxury-focused messaging, we transformed perceptions.\n\nThe campaign successfully repositioned Thailand from a mass-market beach destination to a place of sophisticated experiences, cultural richness, and aspirational luxury. By changing how high-value travelers saw Thailand, we opened doors to a more profitable, engaged audience segment.",
    year: 2024, services: ['Tourism Marketing', 'Brand Film', 'Social Media'],
    colorTheme: '#00a86b', accent: '#00cc7a', gradFrom: '#001a0f', gradTo: '#000d06',
    image: YT('BglRilfoGOA'), youtube: 'BglRilfoGOA', order: 20,
  },
  {
    id: 21, slug: 'canapure-canola-oil', clientName: 'Canapure Canola Oil', title: 'Getting India To Switch To Healthy Oil',
    category: 'Food · FMCG',
    shortDescription: "Building familiarity for an unknown oil category and establishing it as a healthy alternative perfect for Indian cooking.",
    concept: "The challenge was building familiarity for an unknown oil category and establishing it as a healthy alternative, building on the strength of its Canadian heritage. The insight: canola helps fight cholesterol and aims to be a healthy alternative to olive oil — but unlike olive oil, it is fantastic for the Indian style of cooking.\n\nThe outcome: healthy oil leads to a healthy you. A healthy you gives you the opportunity to do more — it allows you to say 'CAN' to everything.\n\nThrough product education, lifestyle positioning, and culturally relevant messaging, the campaign successfully introduced a new category to Indian households. By making canola feel both healthy AND practical for Indian cooking (unlike olive oil), we created a unique market position and drove adoption among health-conscious Indian families.",
    year: 2024, services: ['FMCG Marketing', 'Brand Strategy', 'Social Media'],
    colorTheme: '#ffd700', accent: '#ffec21', gradFrom: '#1a1a00', gradTo: '#0d0d00',
    image: YT('m-ekod_mEzk'), youtube: 'm-ekod_mEzk', order: 21,
  },
  {
    id: 32, slug: 'gsk-yeh-science-hai', clientName: 'GSK', title: 'Yeh Science Hai',
    category: 'Pharma · Health Awareness',
    shortDescription: "Turning the surprising science of shingles into relatable, everyday conversations — because the most surprising health facts aren't myths, they're simply science.",
    concept: "Many people believe shingles is a rare condition or simply a skin problem. The reality is that it is caused by the reactivation of the chickenpox virus that already exists in the body.\n\nYeh Science Hai simplifies this scientific fact through relatable conversations and everyday observations. By turning complex medical information into easy-to-understand moments, the campaign helps people understand their risk, recognize the importance of prevention, and take informed action.\n\nBecause sometimes the most surprising health facts aren't myths or coincidences. They're simply science. Yeh Science Hai.",
    year: 2026, services: ['Brand Film', 'Health Awareness', 'Content Production', 'Social Media'],
    colorTheme: '#f36f21', accent: '#f36f21', gradFrom: '#3a1c05', gradTo: '#190b02',
    image: 'https://res.cloudinary.com/dna8mp2n7/video/upload/so_2/v1782721426/CP_45SEC_1920x1080_WA_o3syft.jpg',
    videos: [
      'https://res.cloudinary.com/dna8mp2n7/video/upload/v1782721426/CP_45SEC_1920x1080_WA_o3syft.mp4',
      'https://res.cloudinary.com/dna8mp2n7/video/upload/v1782721425/DB_40SEC_1920x1080_WA_vbcigp.mp4',
    ],
    order: 22,
  },

  /* ─────────────────────────── TECH / DIGITAL TRANSFORMATION ─────────────────────────── */
  {
    id: 22, slug: 'lipton-squid-game', clientName: 'Lipton', title: 'Lipton x Squid Game: A Gamified Brand Experience',
    category: 'Gamified Experience · Web Game', track: 'tech',
    shortDescription: 'A mobile-first web game for Lipton’s Squid Game-inspired campaign, turning teatime into an interactive challenge that drove participation, repeat gameplay, and deep brand engagement.',
    overview: 'For Lipton, TSBI built an interactive gamified experience inspired by the thrill and precision of Squid Game. The campaign transformed a brand collaboration into a playable digital experience where users could participate, score, and engage with Lipton in a fun and memorable way. The game connected the idea of brewing the perfect cup of tea with the precision required to achieve the perfect score, making the brand message feel natural within the gameplay.',
    challenge: 'Lipton wanted an experience that went beyond regular campaign communication. The objective was to make users actively engage with the brand instead of only viewing content — creating buzz, encouraging repeat participation, and making the Lipton x Squid Game association feel exciting, relevant, and culturally engaging.',
    idea: 'We created a Squid Game-inspired tea challenge where users had to navigate obstacles, collect cups, and aim for the highest score. The core thought was simple: just like the perfect brew, the perfect score needs timing, focus, and precision — turning the campaign message into an interactive experience users could play, enjoy, and remember.',
    experienceIntro: 'A lightweight, mobile-first web experience accessible instantly through a link.',
    experienceItems: ['Mobile-first gameplay', 'Simple tap-based controls', 'Lipton-branded game environment', 'Squid Game-inspired challenge elements', 'Score tracking', 'Repeat-play mechanics', 'Campaign performance tracking'],
    impact: [{ value: '29,752', label: 'Attempts' }, { value: '11,146', label: 'Unique Players' }, { value: '455 hrs', label: 'Total Gameplay' }],
    whyItWorked: 'The campaign made users part of the brand story. Instead of simply watching content, users actively participated. The game format encouraged replay, competition, and longer interaction time, helping Lipton build stronger recall and engagement.',
    concept: 'A mobile-first gamified experience inspired by Squid Game, built to drive participation, repeat gameplay, and brand engagement for Lipton.',
    year: 2024, services: ['Game Concept & Experience Design', 'UI/UX Design', 'Web Game Development', 'Mobile-First Interaction Design', 'Campaign Technology Execution', 'Performance Tracking'],
    colorTheme: '#e0197d', accent: '#e0197d', gradFrom: '#3a0a2a', gradTo: '#15001a',
    image: '/tech/1.png', order: 22,
  },
  {
    id: 23, slug: 'brooke-bond-red-label', clientName: 'Brooke Bond Red Label', title: 'Red Label: Forging Stronger Bonds Beyond the Game',
    category: 'Integrated Campaign · Gamified Experience', track: 'tech',
    shortDescription: 'An IPL-led integrated campaign combining a digital film, gamified couple experience, and retail activation to bring the brand thought “Strong Tea, Stronger Bonds” alive.',
    overview: 'For Brooke Bond Red Label, TSBI tapped into IPL’s high-energy cultural moment to create a campaign that encouraged couples to connect, laugh, and bond over playful differences. The campaign reframed everyday couple clashes as opportunities for connection — through a high-reach digital film, an interactive Test Your Bond experience, and immersive retail activations, moving from screens to shelves.',
    challenge: 'Red Label wanted to stay relevant during the IPL season while remaining true to its core promise of togetherness. The campaign needed to go beyond regular cricket-led communication and create a more emotional, participative experience for couples.',
    idea: 'IPL often brings playful disagreements at home — different teams, different opinions, fun debates between couples. We turned this cultural tension into a bonding moment: like a perfectly brewed cup of tea, strong relationships are made with love, patience, and understanding.',
    experienceIntro: 'A gamified couple experience where users could enter a room code, answer fun questions together, and discover how strong their bond was.',
    experienceItems: ['High-reach digital film', 'Couple-based gamified web experience', 'Room-code based participation', 'Fun relationship questions', 'Retail “How Strong Is Your Bond?” activation', 'Campaign creatives and adaptations'],
    impact: [{ value: '2MN+', label: 'Hearts Reached' }, { value: '1,500+', label: 'Bonds Strengthened' }],
    whyItWorked: 'The campaign connected a mass cultural moment with a human relationship insight. Instead of only placing the brand around IPL, TSBI used the season’s emotional energy to create a meaningful interaction between couples — making Red Label part of their bonding story.',
    concept: 'An IPL-led integrated campaign that combined film, gamification, and retail activation to turn couple clashes into moments of connection.',
    year: 2025, services: ['Campaign Concept', 'Digital Film Extension', 'Gamified Experience Design', 'UI/UX Design', 'Web Game Development', 'Retail Activation Experience', 'Campaign Technology Execution', 'Creative Adaptations'],
    colorTheme: '#c4161c', accent: '#e02a30', gradFrom: '#3a0a0c', gradTo: '#1a0405',
    image: '/tech/2.png', order: 23,
  },
  {
    id: 24, slug: 'zydus-flu-protection', clientName: 'Zydus India', title: 'India’s Flu Protection: Making Prevention Easier to Access',
    category: 'Healthcare · Vaccination Portal', track: 'tech',
    shortDescription: 'A flu awareness and vaccination portal enabling users to find nearby clinics and allowing doctors to register their clinics — turning awareness into action-led healthcare support.',
    overview: 'For Zydus, TSBI created a digital flu awareness and vaccination portal designed to make flu prevention more accessible. The platform helped users understand the importance of flu vaccination, locate nearby clinics, and connect with registered healthcare professionals — while also letting doctors and clinics register themselves, bridging awareness, discovery, and healthcare action.',
    challenge: 'Flu vaccination awareness is often limited, especially among high-risk groups such as children, pregnant women, the elderly, and frequent travellers. Zydus needed a platform that could educate people, simplify clinic discovery, and encourage users to speak to a doctor about flu vaccination.',
    idea: 'We created India’s Flu Protection as a simple, accessible portal connecting awareness with action. The message “Flu Vaccine Liya Kya?” made the communication direct, memorable, and easy to respond to — helping users immediately act by finding nearby clinics and accessing relevant information.',
    experienceIntro: 'A healthcare utility with clear information and simple user journeys.',
    experienceItems: ['Flu awareness content', 'High-risk group education', 'Clinic finder experience', 'Doctor and clinic registration flow', 'Location-based clinic discovery', 'Campaign communication support', 'Responsive website experience'],
    impact: [{ label: 'Easier access to flu care — users moved from awareness to finding nearby clinics' }, { label: 'Stronger doctor–patient connection through a searchable clinic network' }, { label: 'A purpose-led digital utility, not just awareness communication' }],
    whyItWorked: 'The platform solved a real user problem. Instead of only telling people about flu vaccination, it gave them a practical next step. Education, clinic discovery, and doctor registration made the campaign useful, credible, and scalable for a healthcare audience.',
    concept: 'A flu awareness and vaccination portal built for Zydus India, helping users find nearby clinics and enabling doctors to register their clinics for better healthcare access.',
    year: 2024, services: ['Healthcare Website Development', 'Portal Strategy', 'UI/UX Design', 'Clinic Finder Experience', 'Doctor Registration Flow', 'Frontend & Backend Development', 'Campaign Landing Page', 'Digital Awareness Support'],
    colorTheme: '#0088cc', accent: '#0099dd', gradFrom: '#03263a', gradTo: '#001019',
    image: '/tech/3.png', order: 24,
  },
  {
    id: 25, slug: 'zydus-vaxiflu', clientName: 'Zydus Vaxiflu', title: 'Zydus Vaxiflu: A One-Stop Flu Vaccination Microsite',
    category: 'Healthcare · Microsite', track: 'tech',
    shortDescription: 'A healthcare-focused microsite helping patients, caregivers, and healthcare professionals access reliable flu vaccination information, clinic discovery, and doctor registration support.',
    overview: 'For Zydus Vaxiflu, TSBI built a dedicated flu vaccination microsite designed to simplify awareness, education, and access. The platform acted as a one-stop destination where users could learn about flu vaccination, understand its relevance for different audience groups, find nearby clinics, and connect with registered doctors.',
    challenge: 'Flu vaccination awareness can feel fragmented, with users searching across multiple sources for reliable information. Zydus needed a clear, credible, easy-to-use platform that could educate users, support clinic discovery, and encourage people to speak to healthcare professionals.',
    idea: 'We built the microsite around the message “Flu Season? Be Ready With Vaxiflu.” and three simple pillars — Protect. Prepare. Prevent. The objective was to convert awareness into action through a useful healthcare platform where users could learn, search, and take the next step.',
    experienceIntro: 'Informative, clean, and accessible for patients, caregivers, and doctors.',
    experienceItems: ['Flu vaccination awareness content', 'Information for high-risk groups', 'Why Vaccinate section', 'Clinic finder experience', 'Doctor registration flow', 'Campaign communication support', 'Responsive microsite design'],
    impact: [{ value: '2.3K', label: 'Avg Daily Website Visitors' }, { value: '3.8K', label: 'Doctors Registered' }],
    whyItWorked: 'The microsite combined healthcare education with practical utility. Rather than only telling users about flu prevention, it helped them act — finding clinics, understanding vaccination, and connecting with professionals — creating a scalable platform supporting both awareness and access.',
    concept: 'A flu vaccination microsite built for Zydus Vaxiflu, offering reliable vaccination information, clinic discovery, and doctor registration support.',
    year: 2024, services: ['Microsite Strategy', 'Healthcare Website Design', 'UI/UX Design', 'Frontend Development', 'Backend Development', 'Clinic Finder Integration', 'Doctor Registration Flow', 'Content Structuring', 'Campaign Landing Page Development'],
    colorTheme: '#00a39a', accent: '#12b8ae', gradFrom: '#042a28', gradTo: '#001312',
    image: '/tech/4.png', order: 25,
  },
  {
    id: 26, slug: 'vatika-nourishing-oils', clientName: 'Vatika Nourishing Oils', title: 'Vatika Nourishing Oils: A Seamless Digital Journey for Global Audiences',
    category: 'Website · Multilingual', track: 'tech',
    shortDescription: 'A multilingual English and Arabic website creating a premium product discovery experience through visual storytelling, video-led flow, and ingredient-inspired design.',
    overview: 'For Vatika Nourishing Oils, TSBI created a multilingual website experience designed for global audiences across English and Arabic markets. The website brought Vatika’s product range to life through rich visuals, smooth content flow, and a clean product-led interface — helping users explore variants while keeping the brand world immersive, modern, and easy to navigate.',
    challenge: 'Vatika needed a digital experience that could communicate effectively across regions and languages while maintaining strong brand consistency — showcasing the portfolio, supporting English and Arabic audiences, and making product discovery feel simple yet premium.',
    idea: 'We created a multilingual website that positioned Vatika as a modern, global hair care brand, focusing on visual storytelling — product-led sections, ingredient-inspired colours, lifestyle imagery, and smooth browsing interactions to guide users through the brand and its variants.',
    experienceIntro: 'Immersive without becoming heavy or cluttered.',
    experienceItems: ['English and Arabic language support', 'Product-led website flow', 'Ingredient-inspired visual sections', 'Variant-wise product storytelling', 'Video integration', 'Smooth navigation', 'Responsive website experience', 'Premium brand interface'],
    impact: [{ label: 'Stronger global accessibility across English & Arabic audiences' }, { label: 'Better product discovery through ingredient-led storytelling' }, { label: 'A premium brand experience through immersive visuals & polished interactions' }],
    whyItWorked: 'The website combined localization with strong visual storytelling. Instead of a basic product catalogue, each product felt distinct and memorable — multilingual support, video-led storytelling, and ingredient-inspired visuals delivered an experience that felt both global and brand-specific.',
    concept: 'A multilingual English and Arabic website built for Vatika Nourishing Oils, designed to create a seamless product discovery experience through visual storytelling and ingredient-led design.',
    year: 2024, services: ['Multilingual Website Development', 'UI/UX Design', 'Frontend Development', 'Arabic Language Support', 'Product Page Design', 'Visual Storytelling', 'Video Integration', 'Responsive Web Experience', 'Brand Website Execution'],
    colorTheme: '#2e7d32', accent: '#3a9c40', gradFrom: '#0c2410', gradTo: '#050d07',
    image: '/tech/5.png', order: 26,
  },
  {
    id: 27, slug: 'bevzilla', clientName: 'Bevzilla', title: 'Bevzilla: End-to-End Solutions for a New-Age Brand Launch',
    category: 'Brand Launch · Commerce Ecosystem', track: 'tech',
    shortDescription: 'A complete launch ecosystem covering branding, packaging, website, social media, media, SEO, and e-commerce presence to help the brand enter the market with a bold, digitally ready identity.',
    overview: 'For Bevzilla, TSBI delivered an end-to-end brand and digital commerce ecosystem for a new-age brand entering the market — from brand identity and packaging to website development, social media, media planning, SEO, and e-commerce presence. The objective was a launch-ready brand world that looked consistent, modern, and memorable across every consumer touchpoint.',
    challenge: 'As a new brand, Bevzilla needed more than a website or logo — it needed a complete digital and visual ecosystem to look credible, relevant, and ready for discovery, with a strong identity, standout packaging, a digital-first website, marketplace presence, social communication, and consistency across touchpoints.',
    idea: 'We built Bevzilla as a bold, youthful, and trend-first brand — high-energy visuals, punchy typography, strong colour treatment, and modern layouts — a brand that belongs in today’s digital-first consumer world, not just on shelves or marketplaces.',
    experienceIntro: 'A connected launch ecosystem across brand, digital, social, and commerce.',
    experienceItems: ['Brand identity development', 'Packaging design', 'Website design and development', 'E-commerce presence support', 'Marketplace readiness', 'Social media creative', 'Media planning', 'SEO support', 'Launch communication assets'],
    impact: [{ label: 'A complete brand launch ecosystem across identity, packaging, web, social, media, SEO & e-commerce' }, { label: 'Stronger market readiness across key consumer touchpoints' }, { label: 'Trend-led brand positioning that feels young, bold, and relevant' }],
    whyItWorked: 'Every brand touchpoint was created as part of one connected ecosystem. Instead of treating branding, website, packaging, social, and e-commerce separately, TSBI built a unified launch journey — so wherever consumers discovered Bevzilla, the brand looked consistent, confident, and market-ready.',
    concept: 'A complete launch ecosystem built for Bevzilla, covering branding, packaging, website, social media, SEO, media, and e-commerce support.',
    year: 2024, services: ['Brand Identity', 'Packaging Design', 'Website Design & Development', 'E-Commerce Setup Support', 'Marketplace Support', 'Social Media Creative', 'Media Planning', 'SEO', 'Campaign Visual Language', 'Launch Communication'],
    colorTheme: '#ff5a1f', accent: '#ff6a2f', gradFrom: '#2a0f04', gradTo: '#140702',
    image: '/tech/6.png', order: 27,
  },
  {
    id: 28, slug: 'sandu', clientName: 'Sandu', title: 'Sandu: Taking 125 Years of Ayurvedic Trust Into the Digital Era',
    category: 'Digital Transformation · Ayurveda', track: 'tech',
    shortDescription: 'Modernizing Sandu’s digital presence through e-commerce, SEO, social media, packaging, website development, and brand collaborations — while keeping its 125-year Ayurvedic legacy at the centre.',
    overview: 'For Sandu, TSBI helped bring a 125-year-old Ayurvedic legacy into a modern, digital-first brand ecosystem. The work strengthened Sandu’s lifestyle presence across e-commerce, SEO, social media, packaging, website development, and brand collaborations — retaining deep heritage while making it relevant, accessible, and engaging for today’s wellness-focused consumers.',
    challenge: 'Sandu had strong legacy value and trust built over generations. The challenge was to translate that credibility into a modern digital experience without losing authenticity — improving visibility, product discovery, social communication, packaging, and making Ayurveda relevant to a younger, lifestyle-driven audience.',
    idea: 'We shaped the direction around “125 Years of Trust, Now Redefining Your Lifestyle.” positioning Sandu not just as a heritage Ayurveda brand, but as a wellness partner for modern everyday life — combining legacy-led storytelling with digital-first execution.',
    experienceIntro: 'A more modern and connected presence across the digital and brand ecosystem.',
    experienceItems: ['E-commerce support', 'SEO support', 'Website development', 'Social media creative', 'Product packaging support', 'Brand collaboration support', 'Lifestyle-led content', 'Campaign communication', 'Digital brand strategy'],
    impact: [{ label: 'Stronger digital presence — legacy translated into a modern ecosystem' }, { label: 'Improved product discoverability via e-commerce and SEO' }, { label: 'Modern Ayurveda communication & expanded brand visibility' }],
    whyItWorked: 'The work balanced heritage with modern relevance. Instead of moving away from Sandu’s legacy, TSBI used its 125 years of trust as the foundation for a stronger digital identity — website, SEO, e-commerce, social, packaging, and collaborations forming a connected ecosystem that felt rooted, credible, and future-ready.',
    concept: 'A digital transformation ecosystem built for Sandu, bringing its 125-year Ayurvedic legacy into the modern era through e-commerce, SEO, website development, social media, packaging, and brand collaborations.',
    year: 2024, services: ['E-Commerce Support', 'SEO', 'Website Development', 'Social Media Creative', 'Product Packaging', 'Brand Collaboration Support', 'Digital Brand Strategy', 'Campaign Communication', 'Lifestyle-Led Content'],
    colorTheme: '#4a7a00', accent: '#5c9410', gradFrom: '#14200a', gradTo: '#080d04',
    image: '/tech/7.png', order: 28,
  },
  {
    id: 29, slug: 'logistics-websites', clientName: 'New Globe Group & NCS', title: 'Logistics Websites: Stronger Digital Presence for New Globe Group & NCS',
    category: 'Logistics · Corporate Websites', track: 'tech',
    shortDescription: 'Responsive logistics websites for New Globe Group and Neutral Consolidation Services, helping the brands improve online presence, build client confidence, and generate stronger business enquiries.',
    overview: 'For New Globe Group and Neutral Consolidation Services, TSBI created professional logistics websites designed to communicate credibility, services, and business capabilities clearly — translating each brand’s operational strength, legacy, and expertise into a clean, structured, and trustworthy digital experience.',
    challenge: 'Logistics businesses depend heavily on reputation and offline networks, yet today’s clients expect a strong digital presence before making enquiries. The websites needed to showcase services, build trust, make enquiry and quotation requests easy, and work smoothly across desktop and mobile.',
    idea: 'We created modern, responsive logistics websites that acted as digital business gateways — functional, credible, and conversion-oriented. Rather than a static company profile, the platforms helped users understand services, explore capabilities, and quickly act through enquiry and quotation forms.',
    experienceIntro: 'Structured to make information easy to find and enquiries easy to submit.',
    experienceItems: ['Corporate website design', 'Service-led content structure', 'Responsive website development', 'Request-a-quote forms', 'Enquiry forms', 'Track-and-trace support sections', 'Careers and CSR pages', 'Contact and lead generation flows', 'Mobile optimization'],
    impact: [{ label: 'Stronger, more professional online presence' }, { label: 'Enhanced client confidence before making an enquiry' }, { label: 'Increased lead generation through quotation & enquiry flows' }],
    whyItWorked: 'The project solved both a branding and a business problem. The websites didn’t just showcase the companies — they created a structured digital pathway for clients to understand, trust, and contact the brands, turning the sites into active business tools.',
    concept: 'Responsive logistics websites built for New Globe Group and Neutral Consolidation Services, designed to strengthen digital presence, improve client trust, and support enquiry generation.',
    year: 2024, services: ['Website Design & Development', 'UI/UX Design', 'Responsive Web Development', 'Lead Generation Form Setup', 'Content Structuring', 'Corporate Website Strategy', 'Logistics Visual Language', 'Mobile Optimization'],
    colorTheme: '#1a6aff', accent: '#2a7bff', gradFrom: '#06183a', gradTo: '#020a1a',
    image: '/tech/8.png', order: 29,
  },
  {
    id: 30, slug: 'thank-you-fighter', clientName: 'Viacom18 Studios', title: 'Thank You Fighter: Connecting Audiences to India’s Real Heroes',
    category: 'Interactive Platform · Film Campaign', track: 'tech',
    shortDescription: 'An interactive tribute platform for Viacom18 Studios’ Fighter, enabling fans to send thank-you notes to Indian Air Force personnel and turning the film’s patriotic emotion into a meaningful digital experience.',
    overview: 'For Viacom18 Studios, TSBI built a digital engagement platform for the film Fighter, designed to help audiences connect emotionally with the real-life heroes of the Indian Air Force. The campaign transformed the film’s patriotic sentiment into an interactive tribute experience where fans could send thank-you messages to Air Force personnel and celebrate their courage, service, and sacrifice.',
    challenge: 'Fighter carried a strong emotional and patriotic narrative. Viacom18 Studios needed a digital experience that could extend this feeling beyond the screen and let audiences actively participate in the film’s tribute to India’s real heroes — emotional, respectful, easy to use, and campaign-ready.',
    idea: 'We built Thank You Fighter as a tribute-led platform where audiences could send heartfelt messages to the Indian Air Force. The core thought: when Bollywood salutes Bharat’s bravest, every fan should get a chance to say thank you — turning a one-way film promotion into a participative experience.',
    experienceIntro: 'A patriotic visual language with a simple user journey.',
    experienceItems: ['Interactive tribute platform', 'Thank-you note submission flow', 'Mobile-first web experience', 'Patriotic design language', 'Sky, aircraft, and defence-inspired visuals', 'Fan participation journey', 'Cast and celebrity amplification support', 'Campaign technology execution'],
    impact: [{ label: 'A fan tribute platform for the Indian Air Force' }, { label: 'Cast messages connecting Bollywood talent with real-life fighters' }, { label: 'Boosted emotional engagement — reinforcing Fighter as a tribute beyond entertainment' }],
    whyItWorked: 'The campaign gave people a role in the story. Instead of only watching the film’s patriotic message, audiences could participate in it. The simple action of sending a thank-you note made the campaign personal, emotional, and memorable — blending film marketing, fan participation, and national pride.',
    concept: 'An interactive tribute platform built for Fighter, allowing fans to send thank-you notes to Indian Air Force personnel and connect with the film’s patriotic message.',
    year: 2024, services: ['Campaign Microsite Development', 'Digital Experience Design', 'UI/UX Design', 'Frontend Development', 'Interactive Tribute Platform', 'Mobile-First Web Experience', 'Film Marketing Support', 'Campaign Technology Execution'],
    colorTheme: '#1565c0', accent: '#1f7ad6', gradFrom: '#04183a', gradTo: '#010a1c',
    image: '/tech/9.png', order: 30,
  },
  {
    id: 31, slug: 'lulu-wheel-of-fortune', clientName: 'LuLu Hypermarket', title: 'LuLu Wheel of Fortune: Turning Rewards Into an Interactive Experience',
    category: 'Gamified Experience · Web Game', track: 'tech',
    shortDescription: 'An interactive Wheel of Fortune website allowing customers to spin, participate, and win exciting prizes through a fun gamified experience.',
    overview: 'For LuLu Hypermarket, TSBI built a digital Wheel of Fortune experience designed to make customer engagement more playful, rewarding, and interactive — transforming a simple promotional activity into a digital-first game where users could participate instantly, spin the wheel, and experience the excitement of winning rewards.',
    challenge: 'LuLu wanted to engage customers beyond regular promotional communication. The challenge was to create an experience that felt exciting, easy to access, and rewarding — while encouraging users to actively interact with the brand.',
    idea: 'We built a digital spin-the-wheel game where customers could participate and stand a chance to win prizes. The core thought was simple: people love the excitement of chance, rewards, and instant participation — giving customers a reason to spend time with the brand and enjoy the interaction.',
    experienceIntro: 'A simple, high-energy web experience that users could access easily.',
    experienceItems: ['Interactive Wheel of Fortune game', 'Spin-the-wheel gameplay', 'Prize-led engagement flow', 'Festive visual design', 'Bright colours and celebration-led UI', 'Simple user journey', 'Mobile-friendly web experience', 'Campaign technology execution'],
    impact: [{ label: 'Higher customer engagement — customers spent active time with the brand' }, { label: 'Stronger loyalty through a prize-led, memorable interaction' }, { label: 'Easy, accessible campaign participation' }],
    whyItWorked: 'Participation was simple and exciting. The Wheel of Fortune mechanic is familiar, easy to understand, and instantly rewarding — bringing it into a branded digital environment turned campaign attention into active customer engagement and stronger recall.',
    concept: 'An interactive Wheel of Fortune website built for LuLu Hypermarket, allowing customers to spin the wheel and win exciting prizes through a fun gamified experience.',
    year: 2024, services: ['Interactive Website Development', 'Game Concept & Flow', 'UI/UX Design', 'Frontend Development', 'Gamified Campaign Experience', 'Prize-Based Engagement Flow', 'Mobile-Friendly Web Experience', 'Campaign Technology Execution'],
    colorTheme: '#d4006a', accent: '#e8197d', gradFrom: '#2a0a1c', gradTo: '#14040e',
    image: '/tech/10.png', order: 31,
  },
  {
    id: 38, slug: 'happy-patel-khatarnak-jasoos', clientName: 'Happy Patel', title: 'Khatarnak Jasoos',
    category: 'Film Marketing · Spy Comedy',
    shortDescription: "A meme-zone social blitz matching the film's erratic spy-comedy tone — powered by Imran Khan's comeback, viral song reels, moment marketing and AI-led creative.",
    concept: "The social strategy for Happy Patel: Khatarnak Jasoos mirrored the film's fun, erratic, chaotic spy-comedy tone — leaning into meme-style content, self-deprecating humour, quick relatable clips and organic, shareable integrations. The goal was to make the promotion entertaining in itself, turning social feeds into an extension of the movie's absurd, laugh-out-loud vibe.\n\nImran Khan's surprise comeback — his return after nearly a decade — was amplified across platforms, playing on nostalgia and curiosity with shareable content that framed his big-screen return. The feed stayed firmly in the 'meme zone': punchy dialogues, character memes, reaction clips and clumsy, self-roasting 'Happy Patel moments' built for easy sharing.\n\nMusic kept the energy viral — cool, street-styled lyrical videos and song promos for tracks like Aaj Banda Tere Liye Naachega, Phukt Apan and Chaanta Tera were cut as high-energy, meme-friendly reels perfect for user-generated content. Moment marketing rode timely trends, including the Dhurandhar craze, aligning the spy narrative with the culture of the moment, while AI-generated visuals added a surreal, tech-savvy edge true to the film's absurd humour.\n\nThe result: strong virality driven by humour and timeliness, positioning the film as a refreshing laugh riot and boosting awareness — especially among younger, digital-native audiences — without relying solely on traditional star power.",
    year: 2025, services: ['Social Media Strategy', 'Meme Content', 'Song & Lyrical Reels', 'Moment Marketing', 'AI-Led Creative'],
    colorTheme: '#e0641a', accent: '#f0841a', gradFrom: '#2a1400', gradTo: '#140a02',
    image: YT('YEv0zokK140'), youtube: 'YEv0zokK140', order: 38,
  },
  {
    id: 39, slug: 'ek-din', clientName: 'Ek Din', title: 'The Magic of One Day',
    category: 'Film Marketing · Romance',
    shortDescription: "A hopeless-romantic social world built on soulful lyrical videos, AI trend edits and dialogue moments — making the promotion an extension of the film's emotional core.",
    concept: "For Ek Din, we immersed audiences in the film's hopeless-romantic tone through emotional, lyrical and trend-driven content — building a dreamy, relatable world around its themes of fleeting yet life-changing romance, transient connections and the magic of 'one day'. The focus stayed on emotion over gloss, pulling viewers straight into the film's feeling.\n\nBeautiful lyrical videos anchored the campaign — the Arijit Singh-led title track, 'Khwaab Dekhoon' and other Ram Sampath & Irshad Kamil compositions were set to soft visuals, poetic overlays and romantic montages that evoked love, longing and nostalgia.\n\nAI-led trends kept it fresh and shareable — Animal Crossing-style cozy animated interpretations and dreamy anime-inspired edits heightened the fantastical, emotional side of the love story for trend-driven younger audiences. Romance edits, dialogue snippets and slow-motion moments spotlighting Sai Pallavi and Junaid Khan's chemistry were designed to be saved, shared and personally tagged.\n\nThe approach made the promotion feel like an extension of the movie's emotional core — poetic, immersive and deeply romantic — standing out in a crowded Bollywood marketing landscape through creativity, trends and audience participation.",
    year: 2025, services: ['Social Media Strategy', 'Lyrical Videos & Song Promos', 'AI Trend Content', 'Romance & Dialogue Edits'],
    colorTheme: '#c4416e', accent: '#e0197d', gradFrom: '#2a0a1c', gradTo: '#150410',
    image: YT('RCmyr_d3Hi0'), youtube: 'RCmyr_d3Hi0', order: 39,
  },
];

/** Tech / Digital Transformation case studies (subset of the full list). */
export const techCaseStudies = caseStudies.filter((c) => c.track === 'tech');
