import CareersPageClient from './CareersPageClient';
import { getJobListings } from '@/lib/strapi';

const FALLBACK_JOBS = [
  {
    role: 'Account Executive',
    department: 'Client Servicing',
    location: 'Full-time · Mumbai',
    experience: '0 to 3 years',
    summary: undefined,
    responsibilities: [
      'To implement social media solutions developed by the strategy team for various clients of TSBI by using various online social platforms, for example, networking sites, blogs, etc.',
      'To work in tandem with the strategy team to understand reasoning behind the execution.',
      'To help support the clients of TSBI and to ensure that the strategy is adhered to within the context of that assignment.',
      'Use of toolkit to measure and monitor social activities — determine what works, tweak and improve content, communications, etc.',
      'Respond and react to changes within social networks, changes in functionality, methods of engagement, etc.',
      'Monitor and present relevant data, trends, successes, exceptions, etc.',
      'Manage social media campaigns and day-to-day activities and promotions.',
      'Analyze campaigns and translate qualitative data into recommendations and plans for revising the social media campaigns.',
      'Manage presence in social networking sites and posting on relevant blogs.',
      'Work with the Design team to develop creative for the campaign and ensure that the social media tools are kept up to date.',
      'Ensure timely delivery of the project by regular reporting structures and effective client servicing.',
      'Be enthusiastic but responsible.',
    ],
    skills: [
      'Must have experience in digital marketing domain.',
      'Must be flexible, with the ability to multi-task and frequently adjust to changing priorities and timelines.',
      'Ability to write great engaging web copy in a real-time environment that can stimulate user interaction, discussion and engagement.',
      'Excellent communication skills both written and oral.',
      'Team handling and team building skills.',
      'Strong analytical, planning and forecasting skills.',
      'Working in tight deadlines.',
    ],
    email: 'careers@tsbi.in',
  },
  {
    role: 'Copy Lead',
    department: 'Creative',
    location: 'Full-time · Mumbai',
    experience: '4+ years in digital and social media industry',
    summary: 'Our content team is a team of skilled professionals responsible to create everything from blog and article copy to social media content and product descriptions — depending upon what the client requires at a given moment. We are looking for Managers who will be responsible to deliver content across several digital and social platforms which helps in growing the brand.',
    responsibilities: [
      'Be a part of daily ideation, strategy and campaign building for various brands across digital platforms.',
      'Be a part of the Sales/Pitch team for new business opportunity.',
      'Lead and train a team of creative writers.',
      'Supervise and check the copy quality content of the Jr writers.',
      'Write creative copies, scripts, pitch copies, case study content as and when necessary.',
      'Support the Servicing team during client interactions and brief explanations.',
    ],
    skills: [
      'Ability to handle a team and work effectively.',
      'Excellent communication skills.',
      'Creative thinking and writing ability.',
      'Detail-oriented, strong negotiation and communication skills to deal with clients and vendors.',
      'In-depth knowledge of digital platforms.',
      '4 years of prior work experience into the digital and social media industry.',
    ],
    email: 'careers@tsbi.in',
  },
  {
    role: 'Group Account Head',
    department: 'Client Servicing',
    location: 'Full-time · Mumbai',
    experience: '4 years+ experience including significant experience in Digital Marketing',
    summary: 'If you live and breathe digital marketing, we want to talk to you. We are looking for a Digital Marketing Manager to develop, implement, track and optimize our digital marketing campaigns across all digital channels.',
    responsibilities: [
      'Planning digital marketing campaigns, including web, SEO/SEM, email, social media and display advertising.',
      'Measuring and reporting on the performance of all digital marketing campaigns.',
      'Plan and execute all digital marketing, including SEO/SEM, marketing database, email, social media and display advertising campaigns.',
      'Design, build and maintain our social media presence across all digital channels.',
      'Measure and report performance of all digital marketing campaigns, and assess against goals — ROI and KPIs.',
      'Identify trends and insights, and optimize spend and performance based on the insights.',
      'Brainstorm new and creative growth strategies.',
      'Plan, execute, and measure experiments and conversion tests.',
      'Collaborate with internal teams to create landing pages and optimize user experience.',
      'Utilize strong analytical ability to evaluate end-to-end customer experience across multiple channels and customer touch points.',
      'Collaborate with agencies and other vendor partners.',
      'Evaluate emerging technologies. Provide thought leadership and perspective for adoption where appropriate.',
    ],
    skills: [],
    email: 'careers@tsbi.in',
  },
  {
    role: 'Graphic Designer',
    department: 'Creative',
    location: 'Full-time · Mumbai',
    experience: '1+ year',
    summary: undefined,
    responsibilities: [
      'Create designs, concepts, and sample layouts based on knowledge of layout principles and aesthetic design.',
      'Partner with Copywriter and Creative Director to ideate ways to extend brand campaigns across all channels — TV, social, site.',
      'Close collaboration with copywriters to ensure visuals and copy are seamless and deliver on brand messaging.',
      'Stay on voice, on brand and on target.',
      'Adhere to deadlines and timelines, with the ability/flexibility to react to real-time opportunities.',
      'Manage multiple projects effectively and efficiently.',
      'Stay up-to-date with current design trends, techniques and processes; seek out and recommend new best practices.',
      'Work with the analytics team to review and analyze measurement insights to determine necessary adjustments to creative approach.',
    ],
    skills: [],
    software: ['Photoshop', 'Illustrator', 'CorelDraw'],
    email: 'careers@tsbi.in',
  },
  {
    role: 'Media Planner and Buyer',
    department: 'Media & Performance',
    location: 'Full-time · Mumbai',
    experience: '1 to 2 years',
    summary: 'We are looking for a Digital Planner/Buyer who will be responsible for working with clients, agencies, sites/publishers and internal departments to plan, buy and traffic all digital media with a strong emphasis on B2B, local and national sites. Must have both search and display advertising experience. Individual has the ability to ingest research and data, boil it down to relevant insights, plan the media and then clearly and succinctly communicate the plan to individuals internally and externally.',
    responsibilities: [
      'Participates in development and management of effective integrated media plans and buys under the supervision of the Media Director.',
      'Develops objectives, strategies, plans and presentations.',
      'Creates and manages media partner RFP process.',
      'Maintains media plans including changes, budgeting, execution, reporting, optimization and invoice reconciliation.',
      'Executes all digital plans.',
      'Ensures account and creative team is apprised of changes to the placements by producing the Creative and Specs Worksheet.',
      'Develops and executes paid search campaign recommendations and optimizations in Google Awards.',
      'Stays apprised of industry standards, new media programs/opportunities and can advise on new ways to reach targets.',
      'Investigates and utilizes information from syndicated research sources.',
      'Develops and fosters strong relationships with media partners.',
      'Evaluates media opportunities and presents media plans and/or POVs clearly in writing and orally.',
      'Analyzes web metrics, provides campaign effectiveness reports to clients, and recommends optimizations when appropriate to improve media performance.',
      'Handles all digital media billing using monthly tracking reports and invoice reconciliation.',
    ],
    skills: [
      'Strong mathematical abilities required.',
      'Detail oriented and proficient at managing projects and able to multi-task, organize, prioritize and structure workload.',
      'Experience using Google Analytics and other media tools.',
    ],
    email: 'careers@tsbi.in',
  },
];

export default async function CareersPage() {
  const cmsJobs = await getJobListings();

  const jobs = cmsJobs.length
    ? cmsJobs.map((j) => ({
        role: j.role,
        department: j.department,
        location: j.location,
        experience: j.experience,
        summary: undefined as string | undefined,
        skills: j.skills ?? [],
        responsibilities: j.responsibilities ?? [],
        software: undefined as string[] | undefined,
        email: 'careers@tsbi.in',
      }))
    : FALLBACK_JOBS;

  return <CareersPageClient jobs={jobs} />;
}
